export type WeatherStates = 
  | 'sunny'
  | 'clear-night'
  | 'partlycloudy'
  | 'cloudy'
  | 'fog'
  | 'hail'
  | 'rainy'
  | 'snowy'
  | 'snowy-rainy'
  | 'pouring'
  | 'lightning'
  | 'lightning-rainy'
  | 'windy'
  | 'windy-variant'